config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions', omniauth_callbacks: "omniauth_callbacks"
  }
  devise_scope :user do
    authenticated :user do
      root :to => 'experiences#index'
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
    get :feed, on: :collection, to: 'users#myfeed'
  end

  resources :venues, only: [:show, :new, :create]
  resources :experiences do
    resources :dishes, except: [:index]
  end
  post 'search', :to => 'experiences#search'
  resources :relationships,       only: [:create, :destroy]

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  include PgSearch
  default_scope {order("created_at")}
  belongs_to :user

  has_many :dishes, dependent: :destroy
  multisearchable :against => :name
  accepts_nested_attributes_for :dishes
end

app/controllers/experiences_controller.rb
require 'pry'
require 'net/http'
class ExperiencesController < ApplicationController

	def show
		@experience = Experience.find_by(id: params[:id])
	end

  def index
    if params[:user]
      @experiences = Experience.includes(:dishes).where(user_id: params[:user])
    elsif params[:search]
      @experiences = ExperienceSearch.get_search_results(params[:search])
    else
      @experiences = Experience.includes(:dishes).all
    end
  end

  def new
    @experience = Experience.new
    @venue = Venue.new
    @experience.dishes.build
    render :_form
  end

  def create
    @venue = Venue.create_venue(params[:place_id])
    @experience = current_user.experiences.build(name: experience_params[:name])
    @dish = @experience.dishes.build(experience_params[:dish])
    @dish.venue = @venue
    if @venue.save && @experience.save && @dish.save
      redirect_to experiences_path
    else
      render :_form
    end
  end

  def search
    redirect_to :action => "index", :search => params[:search]
  end

  def edit
    @experience = Experience.find_by(id: params[:id])
    if @experience.user == current_user
      render layout: !request.xhr?
    else
      flash[:alert] = "You are not authorized to edit this event"
      redirect_to experience_path(@experience)
    end
  end

  def update
    @experience = Experience.find_by(id: params[:id])
    if @experience.update(name: experience_params[:name])
      redirect_to experience_path(@experience)
    else
      render :edit
    end
  end

  def destroy
    @experience = Experience.find_by(id: params[:id])
    if @experience.user == current_user
      @experience.destroy
      redirect_to experiences_path
    else
      flash[:alert] = "You are not authorized to delete this event"
      redirect_to experience_path(@experience)
    end
  end

  private

  def experience_params
    params.require(:experience).permit(:name, dish: [:id, :title, :dishpicture, :review])
  end

end

app/helpers/experiences_helper.rb
# Get this out of here!  Helpers are for use in views.  This code is _not_ for that.
#
module ExperiencesHelper
  def self.get_search_results(keyword)
    results = []
    PgSearch.multisearch(keyword).each do |object|
      if object.searchable_type == "Dish"
        results << object.searchable.experience unless results.include?(object.searchable.experience)
      elsif object.searchable_type == "User"
        results += object.searchable.experiences
      elsif object.searchable_type == "Experience"
        results << object.searchable
      end
    end
    Dish.venue_search(keyword).each do |object|
      results << object.experience unless results.include?(object.experience)
    end
    return results
  end
end

app/views/experiences/_experience.html.erb
<div class="single-experience" id="<%= experience.id %>" >

  <div class="experience-title">

  <%= link_to "#{experience.user.username}", user_path(experience.user),
              class: "single-user", id: "#{experience.user_id}"%>
              posted
  <%= link_to "#{experience.name}", experience_path(experience),
              class: "single-experience-link" %>
  </div>

  <% if experience.dishes %>
    <div id="<%= experience.id %>" class="owl-carousel carousel-container" >
      <%= render partial: experience.dishes, locals: {experience: experience} %>
    </div>
  <% end %>

</div>

app/views/experiences/_form.html.erb
<% @experience ||= Experience.new %>
<%= bootstrap_form_for @experience do |f| %>
  <% if @experience.errors.any? %>
    <div id = 'error_explanation'>
      <h2>
        <%= pluralize(@experience.errors.count,'error') %> Prohibited this Experience from saving:
      </h2>
      <ul>
        <% @experience.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, label: "Experience Name" %>

  <%= f.fields_for @experience.dishes.build do |dish_form| %>
    <% @experience.dishes.each do |dish| %>
      <% if dish.errors.any? %>
        <div id = 'error_explanation'>
          <h2>
            <%= pluralize(dish.errors.count,'error') %> Prohibited this Dish from saving:
          </h2>
          <ul>
            <% dish.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>

      <div class="form-group">
        <label class="control-label required">Venue</label>
        <input class="controls form-control" type="text" is="autocomplete-input"/>
        <%= image_tag("powered-by-google-on-white.png", alt: 'powered by google') %>
      </div>

      <%= dish_form.text_field :title, label: "Dish" %>
      <%= dish_form.file_field :dishpicture, label: "Picture" %>
      <%= dish_form.text_area :review, label: "Review" %>

  <% end %>
  <%= f.submit "Create Experience" %>
<% end %>

app/views/experiences/_new.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h1 class="modal-title">Record a New Experience</h1>
      </div>
      <div class="modal-body">
        <%= render partial: 'experiences/form' %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/experiences/edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h1 class="modal-title">Edit Experience</h1>
</div>
<div class="modal-body">
  <%= bootstrap_form_for @experience do |f| %>
    <% if @experience.errors.any? %>
      <div id = 'error_explanation'>
        <h2>
          <%= pluralize(@experience.errors.count,'error') %> Prohibited this Experience from saving:
        </h2>
        <ul>
          <% @experience.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <%= f.text_field :name, label: "Experience Name" %>
      <%= f.submit %>
  <% end %>
</div>

app/views/experiences/index.html.erb
<div class="search-bar">
  <%= form_tag search_path, class: "submit" do %>
    <%= text_field_tag :search %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<div id="render-experiences">
  <% if @experiences %>
    <%= render @experiences %>
  <% end %>
</div>

app/views/experiences/show.html.erb
<h2>
  <%= '"' + @experience.name + '"' %> posted by:&nbsp; <%= link_to "#{@experience.user.username}", user_path(@experience.user) %>
</h2>
<div class= "solo-exp-btn-bar">
  <% if @experience.user == current_user %>
    <%= link_to 'Add another dish', new_experience_dish_path(@experience), class: 'btn-default btn-lg', data: {toggle: "modal", target: "#myModal-new-dish"} %>
      &nbsp;
    <%= link_to 'Edit Experience', edit_experience_path(@experience), class: 'btn-default btn-lg', data: {toggle: "modal", target: "#myModal-edit-exp"} %>
      &nbsp;
    <%= link_to 'Delete Experience', experience_path(@experience), class: 'btn-default btn-lg', method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
</div>


<div id="myModal-new-dish" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<div id="myModal-edit-exp" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<% if @experience.dishes %>
  <% @experience.dishes.each do |dish| %>
    <%= render partial: 'dishes/show', locals: {experience: @experience, dish: dish} %>
  <% end %>
<% end %>