config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions', omniauth_callbacks: "omniauth_callbacks"
  }
  devise_scope :user do
    authenticated :user do
      root :to => 'experiences#index'
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
    get :feed, on: :collection, to: 'users#myfeed'
  end

  resources :venues, only: [:show, :new, :create]
  resources :experiences do
    resources :dishes, except: [:index]
  end
  post 'search', :to => 'experiences#search'
  resources :relationships,       only: [:create, :destroy]

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:title, :review]
  pg_search_scope :venue_search, :associated_against => {:venue => [:name, :city]}
  default_scope {order("created_at")}
  belongs_to :experience
  belongs_to :venue

  has_attached_file :dishpicture,
  									:default_url => "/images/No_image_available",
  									styles: { :large => "700x700>", :medium => "500x500>", :thumb => "300x300>" }

  validates_attachment_content_type :dishpicture, :content_type => /^image\/(png|gif|jpeg|jpg)/

  validates :title,:review, presence: true
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

	def show
		@experience = Experience.find(params[:experience_id])
		@dish = Dish.find(params[:id])
	end

	def new
		@experience = Experience.find(params[:experience_id])
		@dish = Dish.new
    render layout: !request.xhr?
	end

	def create
    @venue = Venue.create_venue(params[:place_id])
		@experience = Experience.find(params[:experience_id])
		@dish = @experience.dishes.build(dish_params)
		@dish.venue = @venue
		if @venue.save && @dish.save
			redirect_to experience_path(@experience)
		else
			render :new
		end
	end

  def edit
    @dish = Dish.find_by(id: params[:id])
    @experience = @dish.experience
    if @experience.user == current_user
      render layout: !request.xhr?
    else
      flash[:alert] = "You are not authorized to edit this event"
      redirect_to experience_path(@experience)
    end
  end

  def update
    @dish = Dish.find_by(id: params[:id])
    @experience = @dish.experience
    if params[:place_id] != ""
      @venue = Venue.create_venue(params[:place_id])
      @dish.venue = @venue
    end
    @dish.update(dish_params)
    if @dish.save
      redirect_to experience_path(@experience)
    else
      render :edit
    end
  end

  def destroy
    @dish = Dish.find_by(id: params[:id])
    @experience = @dish.experience
    if @experience.user == current_user
      @dish.destroy
      redirect_to experiences_path
    else
      flash[:alert] = "You are not authorized to delete this event"
      redirect_to experience_path(@experience)
    end
  end

	private

	def dish_params
		params.require(:dish).permit(:dishpicture, :title, :review)
	end
end

app/views/dishes/_dish.html.erb
<div class="single-dish" id="<%= dish.id %>">
  <div class="dish-pic-container">

  	<% if dish.dishpicture.file? %>
  		<%= link_to image_tag(dish.dishpicture.url(:medium), class: 'dish-pic'), experience_path(experience)  %>
  		
  	<% else %>
  		<%= image_tag("No_image_available.svg", size: '500x500', class: 'dish-pic') %>
  		
  	<% end %>

  </div>
  <div class="appear-on-hover dish-description">
    <h3><%= dish.title %></h3>
    <p><%= dish.review.length > 40 ? dish.review[0..30] + "..." : dish.review %></p>
  </div>
</div>

app/views/dishes/_form.html.erb
<%= bootstrap_form_for([@experience, @dish]) do |f| %>

  <% if @dish.errors.any? %>
    <div id = 'error_explanation'>
      <h2>
        <%= pluralize(@dish.errors.count,'error') %> Prohibited this Dish from saving:
      </h2>
      <ul>
        <% @dish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label required">Venue</label>
    <input class="controls form-control sizing" type="text" is="autocomplete-input"/>
    <%= image_tag("powered-by-google-on-white.png", alt: 'powered by google') %>
  </div>

  <%= f.text_field :title, label: "Dish Name", class: "sizing" %>

  <% if @dish.dishpicture.file? %>
    <%= image_tag @dish.dishpicture.url(:thumb) %>
  <% end %>

  <%= f.file_field :dishpicture, label: "Picture" %>
  <%= f.text_area :review, label: "Review", class: "sizing" %>

  <%= f.submit %>
<% end %>

app/views/dishes/_show.html.erb
<div class="dish-info">


  <div class="single-dish">
    <div class="dish-pic-container">
    <%= (dish.dishpicture.file? ? image_tag(dish.dishpicture.url(:large), class: 'dish-pic') : image_tag("No_image_available.svg", size: '150x150', class: 'dish-pic')) %>
    </div>
    <div class="appear-on-hover dish-description">
      <h3><%= dish.title %></h3>
      <p><%= dish.review %></p>
    </div>
  </div>

  <div class="close-up-dish-info">
    <div class="venue-details">
      <p> <%= dish.venue.name %> </p>
      <p> <%= dish.venue.address %> </p>
      <p> <%= dish.venue.city %> <%= dish.venue.state %>, <%= dish.venue.zip %></p>
      <p> <%= dish.venue.phone %></p>
      <p> <%= link_to "#{dish.venue.website}", dish.venue.website %></p>
    </div>
    
    <% if dish.experience.user == current_user %>
      <div class="edit_delete_buttons">
        <%= link_to 'Edit', edit_experience_dish_path(experience, dish), data: {toggle: "modal", target: "#myModal-edit-dish"} %>
        &nbsp;&nbsp;
        <%= link_to 'Delete', experience_dish_path(experience, dish), method: :delete, data: {confirm: 'Are you sure?'}, class: "delete-dish" %>
      </div>
    <% end %>

    <div id="myModal-edit-dish" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

  </div>


</div>

app/views/dishes/edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h1 class="modal-title">Edit Dish</h1>
</div>
<div class="modal-body">
  <%= bootstrap_form_for([@experience, @dish]) do |f| %>

    <% if @dish.errors.any? %>
      <div id = 'error_explanation'>
        <h2>
          <%= pluralize(@dish.errors.count,'error') %> Prohibited this Dish from saving:
        </h2>
        <ul>
          <% @dish.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label class="control-label required">Venue</label>
      <input class="controls form-control" type="text" is="autocomplete-input" placeholder="<%= @dish.venue.name %>"/>
    </div>


    <%= f.text_field :title, label: "Dish" %>

    <% if @dish.dishpicture.file? %>
      <%= image_tag @dish.dishpicture.url(:thumb) %>
    <% end %>

    <%= f.file_field :dishpicture, label: "Picture" %>
    <%= f.text_area :review %>
    <%= f.submit %>

  <% end %>
</div>

app/views/dishes/new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h1 class="modal-title">Add another dish</h1>
</div>
<div class="modal-body">
  <%= render 'form' %>
</div>