config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions', omniauth_callbacks: "omniauth_callbacks"
  }
  devise_scope :user do
    authenticated :user do
      root :to => 'experiences#index'
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
    get :feed, on: :collection, to: 'users#myfeed'
  end

  resources :venues, only: [:show, :new, :create]
  resources :experiences do
    resources :dishes, except: [:index]
  end
  post 'search', :to => 'experiences#search'
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EatMeDrinkme</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyD0aJPt5PYuQ1hyDTfhkw84CliWkiNA4nI"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div id="top-header">
      <div id='top-inner-header'>

        <div id="header-logo">

          <h1>EatMe DrinkMe</h1>

        </div>
        <div class='user-signin-links'>
          <% if user_signed_in? %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </div>
    </div>

    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h1 class="modal-title">Record a New Experience</h1>
          </div>
          <div class="modal-body">
            <%= render partial: 'experiences/form' %>
          </div>
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>

    <div id="navigation-header">
      <% if current_user %>
      <div id="navigation-inner-header">
        <div class="nav-add-dish">
          <%= link_to(image_tag("icons/picture-add-dish.svg", size: '28x28', alt: 'New Experience'), "#", data: {toggle: "modal", target: "#myModal"})  %>
        </div>
        <div class="nav-my-feed">
          <%= link_to(image_tag("icons/picture-my-feed.svg", size: '28x28', alt: 'My Feed'), feed_users_path)  %>
        </div>
        <div class="nav-explore">
          <%= link_to(image_tag("icons/picture-explore.svg", size: '28x28', alt: 'Explore'), experiences_path)  %>
        </div>
        <div class="nav-my-experiences" id="<%= current_user.id %>">
          <%= link_to(image_tag("icons/picture-my-profile.svg", size: '28x28', alt: 'My Experiences', class: "svg"), user_path(current_user)) %>
        </div>
      </div>
      <% end %>
    </div>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </header>

  <div id="main">
    <div id="inner-main">
      <%= yield %>
    </div>
  </div>
  <footer>
    <div id="inner-footer">
      <div>copyright 2015.</div>

      <div>
        <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>
        <% end %>
      </div>

    </div>
  </footer>

</body>
</html>